export const categories = [
  {
    id: 1,
    name: 'Pizza',
    image: require('../assets/images/pizzaIcon.png'),
  },
  {
    id: 2,
    name: 'Burger',
    image: require('../assets/images/burger.png'),
  },
  {
    id: 3,
    name: 'Italian',
    image: require('../assets/images/pasta.png'),
  },
  {
    id: 4,
    name: 'Chinese',
    image: require('../assets/images/dumpling.png'),
  },
  {
    id: 5,
    name: 'Noodles',
    image: require('../assets/images/ramen.png'),
  },
  {
    id: 6,
    name: 'Sweets',
    image: require('../assets/images/cupcake.png'),
  },
  {
    id: 7,
    name: 'Nepali',
    image: require('../assets/images/momo.png'),
  },
  {
    id: 8,
    name: 'Korean',
    image: require('../assets/images/sushi.png'),
  },
  {
    id: 9,
    name: 'Special',
    image: require('../assets/images/cup.png'),
  },
  {
    id: 10,
    name: 'French',
    image: require('../assets/images/spaguetti.png'),
  },
];

export const featured = {
  id: 1,
  title: 'Hot and Spicy',
  description: 'Soft and tender fried chicken',
  restaurants: [
    {
      id: 1,
      name: 'Papa Johns',
      image: require('../assets/images/restaurants/restaurants-2.webp'),
      description: 'Hot and spicy pizzas',
      lng: 38.2145602,
      lat: -85.5324269,
      address: '434 second street',
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
      dishes: [
        {
          id: 1,
          name: 'Momo',
          description: 'Nepali Veg Momo',
          price: 10,
          image: require('../assets/images/momo.png'),
        },
        {
          id: 2,
          name: 'Bakery',
          description: 'Black Forest',
          price: 10,
          image: require('../assets/images/cupcake.png'),
        },
        {
          id: 3,
          name: 'Burger',
          description: 'Chicken burger',
          price: 10,
          image: require('../assets/images/burger.png'),
        },
        {
          id: 4,
          name: 'Noodles',
          description: 'Chinese Noodles',
          price: 10,
          image: require('../assets/images/ramen.png'),
        },
        {
          id: 5,
          name: 'Sushi',
          description: 'Tuna Sushi',
          price: 10,
          image: require('../assets/images/sushi.png'),
        },
        {
          id: 6,
          name: 'Coffee',
          description: 'Cafe Latte',
          price: 10,
          image: require('../assets/images/cup.png'),
        },
      ],
    },
    {
      id: 2,
      name: 'Papa Johns II',
      image: require('../assets/images/restaurants/restaurants-1.webp'),
      description: 'Hot and spicy pizzas',
      lng: 38.2145602,
      lat: -85.5324269,
      address: '434 second street',
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
      dishes: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
        {
          id: 2,
          name: 'Pasta',
          description: 'Cheezy garlic pasta',
          price: 10,
          image: require('../assets/images/pasta.png'),
        },
        {
          id: 3,
          name: 'Chicken',
          description: 'Chicken breasts',
          price: 10,
          image: require('../assets/images/chicken.png'),
        },
        {
          id: 4,
          name: 'Dumplings',
          description: 'Chinese Dumpling',
          price: 10,
          image: require('../assets/images/dumpling.png'),
        },
        {
          id: 5,
          name: 'Sushi',
          description: 'Tuna Sushi',
          price: 10,
          image: require('../assets/images/sushi.png'),
        },
        {
          id: 6,
          name: 'Coffee',
          description: 'Cafe Latte',
          price: 10,
          image: require('../assets/images/cup.png'),
        },
      ],
    },
    {
      id: 3,
      name: 'Papa Johns III',
      image: require('../assets/images/restaurants/restaurants-3.jpeg'),
      description: 'Hot and spicy pizzas',
      lng: 38.2145602,
      lat: -85.5324269,
      address: '434 second street',
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
      dishes: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
        {
          id: 2,
          name: 'Pasta',
          description: 'Cheezy garlic pasta',
          price: 10,
          image: require('../assets/images/pasta.png'),
        },
        {
          id: 3,
          name: 'Chicken',
          description: 'Chicken breasts',
          price: 10,
          image: require('../assets/images/chicken.png'),
        },
        {
          id: 4,
          name: 'Dumplings',
          description: 'Chinese Dumpling',
          price: 10,
          image: require('../assets/images/dumpling.png'),
        },
        {
          id: 5,
          name: 'Sushi',
          description: 'Tuna Sushi',
          price: 10,
          image: require('../assets/images/sushi.png'),
        },
        {
          id: 6,
          name: 'Coffee',
          description: 'Cafe Latte',
          price: 10,
          image: require('../assets/images/cup.png'),
        },
      ],
    },
  ],
};
