export const categories = [
  {
    id: 1,
    name: 'Pizza',
    image: require('../assets/images/pizzaIcon.png'),
  },
  {
    id: 2,
    name: 'Burger',
    image: require('../assets/images/pizzaIcon.png'),
  },
  {
    id: 3,
    name: 'Italian',
    image: require('../assets/images/pizzaIcon.png'),
  },
  {
    id: 4,
    name: 'Chinese',
    image: require('../assets/images/pizzaIcon.png'),
  },
  {
    id: 5,
    name: 'Noodles',
    image: require('../assets/images/pizzaIcon.png'),
  },
  {
    id: 6,
    name: 'Sweets',
    image: require('../assets/images/pizzaIcon.png'),
  },
  {
    id: 7,
    name: 'Nepali',
    image: require('../assets/images/pizzaIcon.png'),
  },
  {
    id: 8,
    name: 'Korean',
    image: require('../assets/images/pizzaIcon.png'),
  },
  {
    id: 9,
    name: 'Special',
    image: require('../assets/images/pizzaIcon.png'),
  },
];

export const featured = {
  id: 1,
  title: 'Hot and Spicy',
  description: 'Soft and tender fried chicken',
  restaurants: [
    {
      id: 1,
      name: 'Papa Johns',
      image: require('../assets/images/restaurants/restaurants-2.webp'),
      description: 'Hot and spicy pizzas',
      lng: 38.2145602,
      lat: -85.5324269,
      address: '434 second street',
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
      dishes: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
        {
          id: 2,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
        {
          id: 3,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
      ],
    },
    {
      id: 2,
      name: 'Papa Johns II',
      image: require('../assets/images/restaurants/restaurants-1.webp'),
      description: 'Hot and spicy pizzas',
      lng: 38.2145602,
      lat: -85.5324269,
      address: '434 second street',
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
      dishes: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
        {
          id: 2,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
        {
          id: 3,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
      ],
    },
    {
      id: 3,
      name: 'Papa Johns III',
      image: require('../assets/images/restaurants/restaurants-3.jpeg'),
      description: 'Hot and spicy pizzas',
      lng: 38.2145602,
      lat: -85.5324269,
      address: '434 second street',
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
      dishes: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
        {
          id: 2,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
        {
          id: 3,
          name: 'Pizza',
          description: 'Cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/pizzaDish.png'),
        },
      ],
    },
  ],
};
